FirstTitle: "Τίποτα, αλλά τίποτα που συμβαίνει δεν είναι τυχαίο
        Είναι απαραίτητο να διατηρηθεί μία ακραία και ακραία προσοχή με ό, τι συμβαίνει"
SecondTitle: "Nada, pero nada de lo que pasa es por casualidad
            Hay que mantenerse con suma y extrema atención con todo lo que acontece"
MainText: "Ως συνέχιση του αγώνα μας λοιπόν, αλλά και για να δείξουμε στους συντρόλλους και τις συντρόλλισσες και τους απανταχού μοναχικούς τρόλληδες και τρόλλισσες ότι ο τρολλικός αγώνας δεν φυλακίζεται και δεν καταστέλλεται, αποφασίσαμε να χτυπήσουμε άμεσα και δραστικά
        <br><br>Η καπιταλιστική δύση έχτισε τα θεμέλια της με αίμα και εκμετάλλευση, επεκτείνοντας την οικονομική ή και στρατιωτική κυριαρχία της σε κάθε γωνιά του πλανήτη, καταδικάζοντας ολόκληρους πληθυσμούς στη φτώχεια, το θάνατο και ρημάζοντας το φυσικό περιβάλλον.
        <br><br>Nα γίνουμε η άμμος στα γρανάζια της καπιταλιστικής μηχανής
            πυροκροτητής στα θεμέλια της ;)
            <br><br>Aκραία σκηνικά
                Eμπιστευτικές φάσεις
                <br><br>Σας περιμένουμε"

