backend:
 name: github
 branch: main
 repo: colibreradio/piloti

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website Settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
         - label: "FirstTitle"
           name: "FirstTitle"
           width: "string"
         - label: "SecondTitle"
           name: "SecondTitle"
           width: "string"
           required: false
         - label: "MainText"
           name: "MainText"
           width: "string"
           required: false
